### ISSUE TITLE
Travis-CI does not work with SMPT server

### ISSUE THREAD

**Issue by jakepeyser** [IBM-Bluemix/logistics-wizard#122]
When running the `server/tests/test_messaging_service.py` test script in Travis-CI, it fails with the following output:
```
======================================================================
ERROR: test_send_email_success (__main__.SendEmailTestCase)
Does the send_email function return successfully?
----------------------------------------------------------------------
Traceback (most recent call last):
  File "server/tests/test_messaging_service.py", line 49, in test_send_email_success
    self.assertIsNone(messaging_service.send_email(test_email, subject, message, 'html'))
  File "/home/travis/build/IBM-Bluemix/logistics-wizard/server/services/messaging.py", line 75, in send_email
    server.ehlo()
  File "/opt/python/2.7.9/lib/python2.7/smtplib.py", line 413, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/opt/python/2.7.9/lib/python2.7/smtplib.py", line 341, in putcmd
    self.send(str)
  File "/opt/python/2.7.9/lib/python2.7/smtplib.py", line 333, in send
    raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first
```

We need to determine what is causing this failure and create a workaround so Travis can test the email sending successfully.

**Comment by jakepeyser** [comment]
Turns out there was leading white-space on the `SMTP_SERVER` env var, causing this issue:
```
$ export SMTP_SERVER= smtp.gmail.com
/home/travis/build.sh: line 45: export: `smtp.gmail.com': not a valid identifier
```

For context, [this is apparently a larger Travis-CI issue](https://github.com/travis-ci/travis-ci/issues/4139) that is still currently open. Removed white-space in https://github.com/IBM-Bluemix/logistics-wizard/pull/133/commits/822e08e01f354e9f8010fe88846226fb1e9fd0c8 and problem has been fixed.
